package top.ridm.maoni.model.DO;

public class LikedDOKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column liked.user_id
     *
     * @mbg.generated Wed Aug 28 17:45:44 CST 2019
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column liked.comment_id
     *
     * @mbg.generated Wed Aug 28 17:45:44 CST 2019
     */
    private Integer commentId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column liked.user_id
     *
     * @return the value of liked.user_id
     *
     * @mbg.generated Wed Aug 28 17:45:44 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column liked.user_id
     *
     * @param userId the value for liked.user_id
     *
     * @mbg.generated Wed Aug 28 17:45:44 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column liked.comment_id
     *
     * @return the value of liked.comment_id
     *
     * @mbg.generated Wed Aug 28 17:45:44 CST 2019
     */
    public Integer getCommentId() {
        return commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column liked.comment_id
     *
     * @param commentId the value for liked.comment_id
     *
     * @mbg.generated Wed Aug 28 17:45:44 CST 2019
     */
    public void setCommentId(Integer commentId) {
        this.commentId = commentId;
    }
}