package top.ridm.maoni.model.DO;

import java.sql.Date;

public class PostDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.id
     *
     * @mbg.generated Wed Aug 28 17:45:44 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.title
     *
     * @mbg.generated Wed Aug 28 17:45:44 CST 2019
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.user_id
     *
     * @mbg.generated Wed Aug 28 17:45:44 CST 2019
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.create_time
     *
     * @mbg.generated Wed Aug 28 17:45:44 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.update_time
     *
     * @mbg.generated Wed Aug 28 17:45:44 CST 2019
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.pageviews
     *
     * @mbg.generated Wed Aug 28 17:45:44 CST 2019
     */
    private Integer pageviews;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.like
     *
     * @mbg.generated Wed Aug 28 17:45:44 CST 2019
     */
    private Integer like;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.comment_count
     *
     * @mbg.generated Wed Aug 28 17:45:44 CST 2019
     */
    private Integer commentCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.description
     *
     * @mbg.generated Wed Aug 28 17:45:44 CST 2019
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.id
     *
     * @return the value of post.id
     *
     * @mbg.generated Wed Aug 28 17:45:44 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.id
     *
     * @param id the value for post.id
     *
     * @mbg.generated Wed Aug 28 17:45:44 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.title
     *
     * @return the value of post.title
     *
     * @mbg.generated Wed Aug 28 17:45:44 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.title
     *
     * @param title the value for post.title
     *
     * @mbg.generated Wed Aug 28 17:45:44 CST 2019
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.user_id
     *
     * @return the value of post.user_id
     *
     * @mbg.generated Wed Aug 28 17:45:44 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.user_id
     *
     * @param userId the value for post.user_id
     *
     * @mbg.generated Wed Aug 28 17:45:44 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.create_time
     *
     * @return the value of post.create_time
     *
     * @mbg.generated Wed Aug 28 17:45:44 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.create_time
     *
     * @param createTime the value for post.create_time
     *
     * @mbg.generated Wed Aug 28 17:45:44 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.update_time
     *
     * @return the value of post.update_time
     *
     * @mbg.generated Wed Aug 28 17:45:44 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.update_time
     *
     * @param updateTime the value for post.update_time
     *
     * @mbg.generated Wed Aug 28 17:45:44 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.pageviews
     *
     * @return the value of post.pageviews
     *
     * @mbg.generated Wed Aug 28 17:45:44 CST 2019
     */
    public Integer getPageviews() {
        return pageviews;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.pageviews
     *
     * @param pageviews the value for post.pageviews
     *
     * @mbg.generated Wed Aug 28 17:45:44 CST 2019
     */
    public void setPageviews(Integer pageviews) {
        this.pageviews = pageviews;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.like
     *
     * @return the value of post.like
     *
     * @mbg.generated Wed Aug 28 17:45:44 CST 2019
     */
    public Integer getLike() {
        return like;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.like
     *
     * @param like the value for post.like
     *
     * @mbg.generated Wed Aug 28 17:45:44 CST 2019
     */
    public void setLike(Integer like) {
        this.like = like;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.comment_count
     *
     * @return the value of post.comment_count
     *
     * @mbg.generated Wed Aug 28 17:45:44 CST 2019
     */
    public Integer getCommentCount() {
        return commentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.comment_count
     *
     * @param commentCount the value for post.comment_count
     *
     * @mbg.generated Wed Aug 28 17:45:44 CST 2019
     */
    public void setCommentCount(Integer commentCount) {
        this.commentCount = commentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.description
     *
     * @return the value of post.description
     *
     * @mbg.generated Wed Aug 28 17:45:44 CST 2019
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.description
     *
     * @param description the value for post.description
     *
     * @mbg.generated Wed Aug 28 17:45:44 CST 2019
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}