package top.ridm.maoni.model.DO;

import java.sql.Date;

public class PostTagDO extends PostTagDOKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post_tag.create_time
     *
     * @mbg.generated Wed Aug 28 17:45:44 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post_tag.update_time
     *
     * @mbg.generated Wed Aug 28 17:45:44 CST 2019
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post_tag.create_time
     *
     * @return the value of post_tag.create_time
     *
     * @mbg.generated Wed Aug 28 17:45:44 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post_tag.create_time
     *
     * @param createTime the value for post_tag.create_time
     *
     * @mbg.generated Wed Aug 28 17:45:44 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post_tag.update_time
     *
     * @return the value of post_tag.update_time
     *
     * @mbg.generated Wed Aug 28 17:45:44 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post_tag.update_time
     *
     * @param updateTime the value for post_tag.update_time
     *
     * @mbg.generated Wed Aug 28 17:45:44 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}