package top.ridm.maoni.DAO.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import top.ridm.maoni.model.DO.LikedDOExample;
import top.ridm.maoni.model.DO.LikedDOKey;

public interface LikedDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table liked
     *
     * @mbg.generated Wed Aug 28 17:45:44 CST 2019
     */
    long countByExample(LikedDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table liked
     *
     * @mbg.generated Wed Aug 28 17:45:44 CST 2019
     */
    int deleteByExample(LikedDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table liked
     *
     * @mbg.generated Wed Aug 28 17:45:44 CST 2019
     */
    int deleteByPrimaryKey(LikedDOKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table liked
     *
     * @mbg.generated Wed Aug 28 17:45:44 CST 2019
     */
    int insert(LikedDOKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table liked
     *
     * @mbg.generated Wed Aug 28 17:45:44 CST 2019
     */
    int insertSelective(LikedDOKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table liked
     *
     * @mbg.generated Wed Aug 28 17:45:44 CST 2019
     */
    List<LikedDOKey> selectByExampleWithRowbounds(LikedDOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table liked
     *
     * @mbg.generated Wed Aug 28 17:45:44 CST 2019
     */
    List<LikedDOKey> selectByExample(LikedDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table liked
     *
     * @mbg.generated Wed Aug 28 17:45:44 CST 2019
     */
    int updateByExampleSelective(@Param("record") LikedDOKey record, @Param("example") LikedDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table liked
     *
     * @mbg.generated Wed Aug 28 17:45:44 CST 2019
     */
    int updateByExample(@Param("record") LikedDOKey record, @Param("example") LikedDOExample example);
}