package top.ridm.maoni.DAO.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import top.ridm.maoni.model.DO.PostDO;
import top.ridm.maoni.model.DO.PostDOExample;

public interface PostDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post
     *
     * @mbg.generated Wed Aug 28 17:45:44 CST 2019
     */
    long countByExample(PostDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post
     *
     * @mbg.generated Wed Aug 28 17:45:44 CST 2019
     */
    int deleteByExample(PostDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post
     *
     * @mbg.generated Wed Aug 28 17:45:44 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post
     *
     * @mbg.generated Wed Aug 28 17:45:44 CST 2019
     */
    int insert(PostDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post
     *
     * @mbg.generated Wed Aug 28 17:45:44 CST 2019
     */
    int insertSelective(PostDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post
     *
     * @mbg.generated Wed Aug 28 17:45:44 CST 2019
     */
    List<PostDO> selectByExampleWithBLOBsWithRowbounds(PostDOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post
     *
     * @mbg.generated Wed Aug 28 17:45:44 CST 2019
     */
    List<PostDO> selectByExampleWithBLOBs(PostDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post
     *
     * @mbg.generated Wed Aug 28 17:45:44 CST 2019
     */
    List<PostDO> selectByExampleWithRowbounds(PostDOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post
     *
     * @mbg.generated Wed Aug 28 17:45:44 CST 2019
     */
    List<PostDO> selectByExample(PostDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post
     *
     * @mbg.generated Wed Aug 28 17:45:44 CST 2019
     */
    PostDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post
     *
     * @mbg.generated Wed Aug 28 17:45:44 CST 2019
     */
    int updateByExampleSelective(@Param("record") PostDO record, @Param("example") PostDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post
     *
     * @mbg.generated Wed Aug 28 17:45:44 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") PostDO record, @Param("example") PostDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post
     *
     * @mbg.generated Wed Aug 28 17:45:44 CST 2019
     */
    int updateByExample(@Param("record") PostDO record, @Param("example") PostDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post
     *
     * @mbg.generated Wed Aug 28 17:45:44 CST 2019
     */
    int updateByPrimaryKeySelective(PostDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post
     *
     * @mbg.generated Wed Aug 28 17:45:44 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(PostDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post
     *
     * @mbg.generated Wed Aug 28 17:45:44 CST 2019
     */
    int updateByPrimaryKey(PostDO record);
}