package top.ridm.maoni.DAO.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import top.ridm.maoni.model.DO.PostTagDO;
import top.ridm.maoni.model.DO.PostTagDOExample;
import top.ridm.maoni.model.DO.PostTagDOKey;

public interface PostTagDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_tag
     *
     * @mbg.generated Wed Aug 28 17:45:44 CST 2019
     */
    long countByExample(PostTagDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_tag
     *
     * @mbg.generated Wed Aug 28 17:45:44 CST 2019
     */
    int deleteByExample(PostTagDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_tag
     *
     * @mbg.generated Wed Aug 28 17:45:44 CST 2019
     */
    int deleteByPrimaryKey(PostTagDOKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_tag
     *
     * @mbg.generated Wed Aug 28 17:45:44 CST 2019
     */
    int insert(PostTagDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_tag
     *
     * @mbg.generated Wed Aug 28 17:45:44 CST 2019
     */
    int insertSelective(PostTagDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_tag
     *
     * @mbg.generated Wed Aug 28 17:45:44 CST 2019
     */
    List<PostTagDO> selectByExampleWithRowbounds(PostTagDOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_tag
     *
     * @mbg.generated Wed Aug 28 17:45:44 CST 2019
     */
    List<PostTagDO> selectByExample(PostTagDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_tag
     *
     * @mbg.generated Wed Aug 28 17:45:44 CST 2019
     */
    PostTagDO selectByPrimaryKey(PostTagDOKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_tag
     *
     * @mbg.generated Wed Aug 28 17:45:44 CST 2019
     */
    int updateByExampleSelective(@Param("record") PostTagDO record, @Param("example") PostTagDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_tag
     *
     * @mbg.generated Wed Aug 28 17:45:44 CST 2019
     */
    int updateByExample(@Param("record") PostTagDO record, @Param("example") PostTagDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_tag
     *
     * @mbg.generated Wed Aug 28 17:45:44 CST 2019
     */
    int updateByPrimaryKeySelective(PostTagDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_tag
     *
     * @mbg.generated Wed Aug 28 17:45:44 CST 2019
     */
    int updateByPrimaryKey(PostTagDO record);
}